name: cbase
channels:
  - conda-forge
  - defaults
  - nsidc

dependencies:
  - python=3.11
  - dask
  - h5py
  - matplotlib
  - netcdf4
  - numpy
  - pyhdf
  - h5netcdf  
  - pytz
  - numexpr  
  - hdf5
  - h5py
  - pygrib
  - pytest  
  - scikit-learn
  - scipy
  - xarray
